# Site settings 配置站点
title: 'Chunyang Lang'
description: 'Research & Coding'
keywords: 'your web keywords, another keywords'
url: 'www.xnmll.cn' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  Homepage: '/'
  #标签: '/tags.html'
  Timeline: '/timeline.html'
  About me: '/about.html'
  #友情链接: '/friendLink.html'

# 博主
author: true
name: 'Chunyang Lang'
NickName: 'xnmll'
webtitle: 'Research & Coding'
bio: ''
about: true
aboutyou: '&emsp;&emsp;My name is Lang Chunyang (郎春阳). I graduated from <a href="http://www.seu.edu.cn">====</a> with ==== in ==== (====). Now, I am a ==== at <a href="http://www.nlpr.ia.ac.cn/nlpren/EN/volumn/home.shtml">====</a>, <a href="http://english.cas.cn">====</a>, supervised by Prof. <a href="http://www.cbsr.ia.ac.cn/users/zlei/">====</a> and Prof. <a href="http://www.cbsr.ia.ac.cn/users/szli">====</a>, where I mainly research on <b>====</b>, <b>====</b>, <b>====</b> and <b>====</b>. <br/>&emsp;&emsp;More to see <a href="/2018/10/07/index.html">here</a>.<br>'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:xnmlllcy@gmail.com'
  weixin: '/assets/wechat.png' # 你的微信二维码存放的地址
  #qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/xnmll'
  #Codepen: ''
  #weibo: ''
  #instagram: ''
  Twitter: 'https://twitter.com/CnXnmll'
  #Dribbble: ''
  #Facebook: ''
  #Google: ''
  zhihu: 'https://www.zhihu.com/people/xnmll01'
  #juejin: ''
  #twitch: ''

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
#friends:
  #jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
